const express = require('express');
const bodyParser = require('body-parser');
const nodemailer = require('nodemailer');
const moment = require('moment');
const path = require('path');
const crypto = require('crypto');

const app = express();
const PORT = process.env.PORT || 8080;

// --- Environment Variables ---
const MAIL_USER = process.env.MAIL_USER || 'testpython230@gmail.com';
const MAIL_PASS = process.env.MAIL_PASS || 'caphjwuafodufsba'; // Use App Password
const ADMIN_API_KEY = process.env.ADMIN_API_KEY || 'YOUR_STRONG_ADMIN_KEY_HERE'; // CHANGE THIS
const RESTAURANT_PHONE = process.env.RESTAURANT_PHONE || '(703) 555-1234'; // Add phone number
const badWords = [
    "2 girls 1 cup",
    "2g1c",
    "4r5e",
    "5h1t",
    "5hit",
    "5ht",
    "@$$",
    "a s s",
    "a s shole",
    "a55",
    "a55hole",
    "a_s_s",
    "abbo",
    "abeed",
    "acrotomophilia",
    "africoon",
    "ahole",
    "alabama hot pocket",
    "alaskan pipeline",
    "alligator bait",
    "alligatorbait",
    "amcik",
    "anal",
    "analannie",
    "analprobe",
    "analsex",
    "andskota",
    "anilingus",
    "anus",
    "apeshit",
    "ar5e",
    "arabush",
    "arabushs",
    "areola",
    "areole",
    "argie",
    "armo",
    "armos",
    "arrse",
    "arschloch",
    "arse",
    "arsehole",
    "aryan",
    "ash0le",
    "ash0les",
    "asholes",
    "ass monkey",
    "ass",
    "ass-fucker",
    "ass-hat",
    "ass-pirate",
    "assbag",
    "assbagger",
    "assbandit",
    "assbang",
    "assbanged",
    "assbanger",
    "assbangs",
    "assbite",
    "assblaster",
    "assclown",
    "asscock",
    "asscowboy",
    "asscracker",
    "asses",
    "assface",
    "assfuck",
    "assfucker",
    "assfukka",
    "assgoblin",
    "assh0le",
    "assh0lez",
    "asshat",
    "asshead",
    "assho1e",
    "asshole",
    "assholes",
    "assholz",
    "asshopper",
    "asshore",
    "assjacker",
    "assjockey",
    "asskiss",
    "asskisser",
    "assklown",
    "asslick",
    "asslicker",
    "asslover",
    "assman",
    "assmaster",
    "assmonkey",
    "assmunch",
    "assmuncher",
    "assnigger",
    "asspacker",
    "asspirate",
    "asspuppies",
    "assrammer",
    "assranger",
    "assshit",
    "assshole",
    "asssucker",
    "asswad",
    "asswhole",
    "asswhore",
    "asswipe",
    "asswipes",
    "auto erotic",
    "autoerotic",
    "ayir",
    "azazel",
    "azz",
    "azzhole",
    "b a s t a r d",
    "b i t c h",
    "b o o b",
    "b!+ch",
    "b!tch",
    "b!tchin",
    "b*tch",
    "b00b",
    "b00bies",
    "b00biez",
    "b00bs",
    "b00bz",
    "b17ch",
    "b1tch",
    "b7ch",
    "babeland",
    "babes",
    "baby batter",
    "baby juice",
    "backdoorman",
    "badfuck",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "balllicker",
    "ballsack",
    "bampot",
    "bangbro",
    "bangbros",
    "bangbus",
    "bareback",
    "barely legal",
    "barelylegal",
    "barenaked",
    "barface",
    "barfface",
    "bassterd",
    "bassterds",
    "bastard",
    "bastardo",
    "bastards",
    "bastardz",
    "basterds",
    "basterdz",
    "bastinado",
    "bazongas",
    "bazooms",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beaney",
    "beaneys",
    "beardedclam",
    "beastality",
    "beastial",
    "beastiality",
    "beastility",
    "beatch",
    "beatoff",
    "beatyourmeat",
    "beaver cleaver",
    "beaver lips",
    "beef curtains",
    "beeyotch",
    "bellend",
    "beotch",
    "bestial",
    "bestiality",
    "bi curious",
    "bi+ch",
    "bi7ch",
    "biatch",
    "bicurious",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bigass",
    "bigbastard",
    "bigbreasts",
    "bigbutt",
    "bigtits",
    "bimbo",
    "bimbos",
    "bint",
    "birdlock",
    "bitch",
    "bitchass",
    "bitched",
    "bitcher",
    "bitchers",
    "bitches",
    "bitchez",
    "bitchin",
    "bitching",
    "bitchslap",
    "bitchtit",
    "bitchy",
    "biteme",
    "bitties",
    "black cock",
    "blackcock",
    "blackman",
    "blacks",
    "blonde action",
    "blonde on blonde action",
    "blonde on blonde",
    "bloodclaat",
    "blow j",
    "blow job",
    "blow your l",
    "blow your load",
    "blowjob",
    "blowjobs",
    "blue waffle",
    "bluegum",
    "bluegums",
    "blumpkin",
    "bo ob",
    "bo obs",
    "boang",
    "boche",
    "boches",
    "boffing",
    "bogan",
    "bohunk",
    "boink",
    "boiolas",
    "bollick",
    "bollock",
    "bollocks",
    "bollok",
    "bollox",
    "bombers",
    "bomd",
    "bondage",
    "boned",
    "boner",
    "boners",
    "bong",
    "boong",
    "boonga",
    "boongas",
    "boongs",
    "boonie",
    "boonies",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "bootee",
    "bootlip",
    "bootlips",
    "boozer",
    "bosch",
    "bosche",
    "bosches",
    "boschs",
    "bosomy",
    "bounty bar",
    "bounty bars",
    "bountybar",
    "brea5t",
    "breastjob",
    "breastlover",
    "breastman",
    "brown shower",
    "brown showers",
    "brunette action",
    "btch",
    "buceta",
    "buddhahead",
    "buddhaheads",
    "buffies",
    "bugger",
    "buggered",
    "buggery",
    "bukake",
    "bukkake",
    "bullcrap",
    "bulldike",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bullshits",
    "bullshitted",
    "bullturds",
    "bumblefuck",
    "bumfuck",
    "bung hole",
    "bung",
    "bunga",
    "bungas",
    "bunghole",
    "bunny fucker",
    "burr head",
    "burr heads",
    "burrhead",
    "burrheads",
    "butchbabes",
    "butchdike",
    "butchdyke",
    "butt plug",
    "butt-pirate",
    "buttbang",
    "buttcheeks",
    "buttface",
    "buttfuck",
    "buttfucker",
    "buttfuckers",
    "butthead",
    "butthole",
    "buttman",
    "buttmuch",
    "buttmunch",
    "buttmuncher",
    "buttpirate",
    "buttplug",
    "buttstain",
    "buttwipe",
    "byatch",
    "c u n t",
    "c-0-c-k",
    "c-o-c-k",
    "c-u-n-t",
    "c.0.c.k",
    "c.o.c.k.",
    "c.u.n.t",
    "c0ck",
    "c0cks",
    "c0cksucker",
    "c0k",
    "cabron",
    "caca",
    "cacker",
    "cahone",
    "camel jockey",
    "camel jockeys",
    "camel toe",
    "cameljockey",
    "cameltoe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "carruth",
    "cawk",
    "cawks",
    "cazzo",
    "chav",
    "cheese eating surrender monkey",
    "cheese eating surrender monkies",
    "cheeseeating surrender monkey",
    "cheeseeating surrender monkies",
    "cheesehead",
    "cheeseheads",
    "cherrypopper",
    "chickslick",
    "china swede",
    "china swedes",
    "chinaman",
    "chinamen",
    "chinaswede",
    "chinaswedes",
    "chinc",
    "chincs",
    "ching chong",
    "ching chongs",
    "chinga",
    "chingchong",
    "chingchongs",
    "chink",
    "chinks",
    "chinky",
    "choad",
    "chocolate rosebuds",
    "chode",
    "chodes",
    "chonkies",
    "chonky",
    "chonkys",
    "chraa",
    "christ killer",
    "christ killers",
    "chug",
    "chugs",
    "chuj",
    "chunger",
    "chungers",
    "chunkies",
    "chunkys",
    "cipa",
    "circlejerk",
    "cl1t",
    "clamdigger",
    "clamdiver",
    "clamps",
    "clansman",
    "clansmen",
    "clanswoman",
    "clanswomen",
    "cleveland steamer",
    "clit",
    "clitface",
    "clitfuck",
    "clitoris",
    "clitorus",
    "clits",
    "clitty",
    "clogwog",
    "clover clamps",
    "clusterfuck",
    "cnts",
    "cntz",
    "cnut",
    "cocain",
    "cocaine",
    "cock",
    "cock-head",
    "cock-sucker",
    "cockbite",
    "cockblock",
    "cockblocker",
    "cockburger",
    "cockcowboy",
    "cockface",
    "cockfight",
    "cockfucker",
    "cockhead",
    "cockholster",
    "cockjockey",
    "cockknob",
    "cockknocker",
    "cockknoker",
    "cocklicker",
    "cocklover",
    "cockmaster",
    "cockmongler",
    "cockmongruel",
    "cockmonkey",
    "cockmunch",
    "cockmuncher",
    "cocknob",
    "cocknose",
    "cocknugget",
    "cockqueen",
    "cockrider",
    "cocks",
    "cockshit",
    "cocksman",
    "cocksmith",
    "cocksmoker",
    "cocksucer",
    "cocksuck",
    "cocksucked",
    "cocksucker",
    "cocksucking",
    "cocksucks",
    "cocksuka",
    "cocksukka",
    "cocktease",
    "cocky",
    "cohee",
    "coital",
    "coitus",
    "cok",
    "cokmuncher",
    "coksucka",
    "condom",
    "coochie",
    "coochy",
    "coolie",
    "coolies",
    "cooly",
    "coon ass",
    "coon asses",
    "coonass",
    "coonasses",
    "coondog",
    "coons",
    "cooter",
    "coprolagnia",
    "coprophilia",
    "copulate",
    "corksucker",
    "cornhole",
    "cra5h",
    "crackcocain",
    "crackpipe",
    "crackwhore",
    "crap",
    "crapola",
    "crapper",
    "crappy",
    "creampie",
    "crotchjockey",
    "crotchmonkey",
    "crotchrot",
    "cuck",
    "cum face",
    "cum licker",
    "cum",
    "cumbubble",
    "cumdumpster",
    "cumfest",
    "cumguzzler",
    "cuming",
    "cumjockey",
    "cumlickr",
    "cumm",
    "cummer",
    "cummin",
    "cumming",
    "cumquat",
    "cumqueen",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cumstain",
    "cumsucker",
    "cumtart",
    "cunilingus",
    "cunillingus",
    "cunn",
    "cunnie",
    "cunnilingus",
    "cunntt",
    "cunny",
    "cunt",
    "cunteyed",
    "cuntface",
    "cuntfuck",
    "cuntfucker",
    "cunthole",
    "cunthunter",
    "cuntlick",
    "cuntlicker",
    "cuntlicking",
    "cuntrag",
    "cunts",
    "cuntslut",
    "cuntsucker",
    "cuntz",
    "curry muncher",
    "curry munchers",
    "currymuncher",
    "currymunchers",
    "cushi",
    "cushis",
    "cyalis",
    "cyberfuc",
    "cyberfuck",
    "cyberfucked",
    "cyberfucker",
    "cyberfuckers",
    "cyberfucking",
    "cybersex",
    "cyberslimer",
    "d0ng",
    "d0uch3",
    "d0uche",
    "d1ck",
    "d1ld0",
    "d1ldo",
    "d4mn",
    "dago",
    "dagos",
    "dahmer",
    "damm",
    "dammit",
    "damn",
    "damnit",
    "darkey",
    "darkeys",
    "darkie",
    "darkies",
    "darky",
    "date rape",
    "daterape",
    "datnigga",
    "dawgie style",
    "dawgie-style",
    "daygo",
    "deapthroat",
    "deep throat",
    "deep throating",
    "deepaction",
    "deepthroat",
    "deepthroating",
    "defecate",
    "deggo",
    "dego",
    "degos",
    "dendrophilia",
    "destroyyourpussy",
    "deth",
    "diaper daddy",
    "diaper head",
    "diaper heads",
    "diaperdaddy",
    "diaperhead",
    "diaperheads",
    "dick pic",
    "dick",
    "dick-ish",
    "dickbag",
    "dickbeater",
    "dickbeaters",
    "dickbrain",
    "dickdipper",
    "dickface",
    "dickflipper",
    "dickforbrains",
    "dickfuck",
    "dickhead",
    "dickheads",
    "dickhole",
    "dickish",
    "dickjuice",
    "dickless",
    "dicklick",
    "dicklicker",
    "dickman",
    "dickmilk",
    "dickmonger",
    "dickpic",
    "dickripper",
    "dicks",
    "dicksipper",
    "dickslap",
    "dickslicker",
    "dicksucker",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dickwhipper",
    "dickwod",
    "dickzipper",
    "diddle",
    "dike",
    "dild0",
    "dild0s",
    "dildo",
    "dildos",
    "dilf",
    "diligaf",
    "dilld0",
    "dilld0s",
    "dillweed",
    "dimwit",
    "dingle",
    "dingleberries",
    "dingleberry",
    "dink",
    "dinks",
    "dipship",
    "dipshit",
    "dipstick",
    "dirsa",
    "dirty pillows",
    "dirty sanchez",
    "dix",
    "dixiedike",
    "dixiedyke",
    "dlck",
    "dog style",
    "dog-fucker",
    "doggie style",
    "doggie",
    "doggie-style",
    "doggiestyle",
    "doggin",
    "dogging",
    "doggy style",
    "doggy-style",
    "doggystyle",
    "dolcett",
    "dominatricks",
    "dominatrics",
    "dominatrix",
    "dommes",
    "dong",
    "donkey punch",
    "donkeypunch",
    "donkeyribber",
    "doochbag",
    "doodoo",
    "doofus",
    "dookie",
    "doosh",
    "dot head",
    "dot heads",
    "dothead",
    "dotheads",
    "double dong",
    "double penetration",
    "doubledong",
    "doublepenetration",
    "douch3",
    "douche bag",
    "douche",
    "douche-fag",
    "douchebag",
    "douchebags",
    "douchewaffle",
    "douchey",
    "dp action",
    "dpaction",
    "dragqueen",
    "dragqween",
    "dripdick",
    "dry hump",
    "dryhump",
    "duche",
    "dudette",
    "dumass",
    "dumb ass",
    "dumbass",
    "dumbasses",
    "dumbbitch",
    "dumbfuck",
    "dumbshit",
    "dumshit",
    "dune coon",
    "dune coons",
    "dupa",
    "dvda",
    "dyefly",
    "dyke",
    "dykes",
    "dziwka",
    "earotics",
    "easyslut",
    "eat my ass",
    "eat my",
    "eatadick",
    "eatballs",
    "eathairpie",
    "eatme",
    "eatmyass",
    "eatpussy",
    "ecchi",
    "ejackulate",
    "ejakulate",
    "ekrem",
    "ekto",
    "enculer",
    "enema",
    "erection",
    "ero",
    "erotic",
    "erotism",
    "esqua",
    "essohbee",
    "ethical slut",
    "evl",
    "excrement",
    "exkwew",
    "extacy",
    "extasy",
    "f u c k e r",
    "f u c k e",
    "f u c k",
    "f u k",
    "f*ck",
    "f-u-c-k",
    "f.u.c.k",
    "f4nny",
    "f_u_c_k",
    "facefucker",
    "fack",
    "faeces",
    "faen",
    "fag",
    "fag1t",
    "fagbag",
    "faget",
    "fagfucker",
    "fagg",
    "fagg1t",
    "fagged",
    "fagging",
    "faggit",
    "faggitt",
    "faggot",
    "faggotcock",
    "faggs",
    "fagit",
    "fagot",
    "fagots",
    "fags",
    "fagt",
    "fagtard",
    "fagz",
    "faig",
    "faigs",
    "faigt",
    "fanculo",
    "fannybandit",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fartknocker",
    "fastfuck",
    "fatah",
    "fatfuck",
    "fatfucker",
    "fatso",
    "fck",
    "fckcum",
    "fckd",
    "fcuk",
    "fcuker",
    "fcuking",
    "fecal",
    "feck",
    "fecker",
    "feg",
    "felatio",
    "felch",
    "felcher",
    "felching",
    "fellate",
    "fellatio",
    "feltch",
    "feltcher",
    "feltching",
    "female squirting",
    "femalesquirtin",
    "femalesquirting",
    "femdom",
    "fetish",
    "ficken",
    "figging",
    "fingerbang",
    "fingerfood",
    "fingerfuck",
    "fingerfucked",
    "fingerfucker",
    "fingerfuckers",
    "fingerfucking",
    "fingerfucks",
    "fingering",
    "fisted",
    "fister",
    "fistfuck",
    "fistfucked",
    "fistfucker",
    "fistfuckers",
    "fistfucking",
    "fistfuckings",
    "fistfucks",
    "fisting",
    "fisty",
    "fitt",
    "flamer",
    "flasher",
    "flikker",
    "flipping the bird",
    "flogthelog",
    "floo",
    "floozy",
    "flydie",
    "flydye",
    "foad",
    "fok",
    "fondle",
    "foobar",
    "fook",
    "fooker",
    "foot fetish",
    "footaction",
    "footfetish",
    "footfuck",
    "footfucker",
    "footjob",
    "footlicker",
    "footstar",
    "foreskin",
    "forni",
    "fornicate",
    "fotze",
    "foursome",
    "fourtwenty",
    "freakfuck",
    "freakyfucker",
    "freefuck",
    "freex",
    "frigg",
    "frigga",
    "frigger",
    "frotting",
    "fucck",
    "fuck",
    "fuck-tard",
    "fucka",
    "fuckable",
    "fuckass",
    "fuckbag",
    "fuckbitch",
    "fuckbook",
    "fuckboy",
    "fuckbrain",
    "fuckbuddy",
    "fuckbutt",
    "fuckd",
    "fucked",
    "fuckedup",
    "fucker",
    "fuckers",
    "fuckersucker",
    "fuckface",
    "fuckfest",
    "fuckfreak",
    "fuckfriend",
    "fuckhead",
    "fuckheads",
    "fuckher",
    "fuckhole",
    "fuckin",
    "fuckina",
    "fucking",
    "fuckingbitch",
    "fuckings",
    "fuckingshitmotherfucker",
    "fuckinnuts",
    "fuckinright",
    "fuckit",
    "fuckknob",
    "fuckme",
    "fuckmeat",
    "fuckmehard",
    "fuckmonkey",
    "fuckn",
    "fucknugget",
    "fucknut",
    "fucknuts",
    "fucknutt",
    "fucknutz",
    "fuckoff",
    "fuckpig",
    "fuckpuppet",
    "fuckr",
    "fucks",
    "fuckstick",
    "fucktard",
    "fucktards",
    "fucktoy",
    "fucktrophy",
    "fuckup",
    "fuckwad",
    "fuckwhit",
    "fuckwhore",
    "fuckwit",
    "fuckwitt",
    "fuckyomama",
    "fuckyou",
    "fudge packer",
    "fudgepacker",
    "fugly",
    "fuk",
    "fukah",
    "fuken",
    "fuker",
    "fukin",
    "fuking",
    "fukk",
    "fukkah",
    "fukken",
    "fukker",
    "fukkin",
    "fukking",
    "fuks",
    "fuktard",
    "fuktards",
    "fukwhit",
    "fukwit",
    "funfuck",
    "futanari",
    "futanary",
    "futkretzn",
    "fuuck",
    "fux",
    "fux0r",
    "fuxor",
    "fvck",
    "fvk",
    "fxck",
    "g-spot",
    "g00k",
    "gae",
    "gai",
    "gang bang",
    "gangbang",
    "gangbanged",
    "gangbanger",
    "gangbangs",
    "ganja",
    "gassyass",
    "gator bait",
    "gatorbait",
    "gay sex",
    "gayass",
    "gaybob",
    "gayboy",
    "gaydo",
    "gaygirl",
    "gaylord",
    "gaymuthafuckinwhore",
    "gays",
    "gaysex",
    "gaytard",
    "gaywad",
    "gayz",
    "geezer",
    "geni",
    "genital",
    "genitals",
    "getiton",
    "gey",
    "gfy",
    "ghay",
    "ghey",
    "giant cock",
    "gigolo",
    "ginzo",
    "ginzos",
    "gipp",
    "gippo",
    "gippos",
    "gipps",
    "girl on top",
    "girl on",
    "girls gone wild",
    "givehead",
    "glans",
    "glazeddonut",
    "goatcx",
    "goatse",
    "god dammit",
    "god damn",
    "god damnit",
    "god-dam",
    "god-damned",
    "godam",
    "godammit",
    "godamn",
    "godamnit",
    "goddam",
    "goddamit",
    "goddamm",
    "goddammit",
    "goddamn",
    "goddamned",
    "goddamnes",
    "goddamnit",
    "goddamnmuthafucker",
    "godsdamn",
    "gokkun",
    "golden shower",
    "goldenshower",
    "golliwog",
    "golliwogs",
    "gonad",
    "gonads",
    "gonorrehea",
    "gonzagas",
    "goo girl",
    "gooch",
    "goodpoop",
    "gook eye",
    "gook eyes",
    "gook",
    "gookeye",
    "gookeyes",
    "gookies",
    "gooks",
    "gooky",
    "gora",
    "goras",
    "goregasm",
    "gotohell",
    "goy",
    "goyim",
    "greaseball",
    "greaseballs",
    "groe",
    "groid",
    "groids",
    "grope",
    "grostulation",
    "group sex",
    "gspot",
    "gstring",
    "gtfo",
    "gub",
    "gubba",
    "gubbas",
    "gubs",
    "guido",
    "guiena",
    "guineas",
    "guizi",
    "gummer",
    "guro",
    "gwailo",
    "gwailos",
    "gweilo",
    "gweilos",
    "gyopo",
    "gyopos",
    "gyp",
    "gyped",
    "gypo",
    "gypos",
    "gypp",
    "gypped",
    "gyppie",
    "gyppies",
    "gyppo",
    "gyppos",
    "gyppy",
    "gyppys",
    "gypsys",
    "h e l l",
    "h o m",
    "h00r",
    "h0ar",
    "h0m0",
    "h0mo",
    "h0r",
    "h0re",
    "h4x0r",
    "hadji",
    "hadjis",
    "hairyback",
    "hairybacks",
    "haji",
    "hajis",
    "hajji",
    "hajjis",
    "half breed",
    "half caste",
    "halfbreed",
    "halfcaste",
    "hamas",
    "hamflap",
    "hand job",
    "handjob",
    "haole",
    "haoles",
    "hapa",
    "hard core",
    "hardcore",
    "hardcoresex",
    "hardon",
    "he11",
    "headfuck",
    "hebe",
    "hebes",
    "heeb",
    "heebs",
    "hells",
    "helvete",
    "hentai",
    "heroin",
    "herp",
    "herpes",
    "herpy",
    "heshe",
    "hijacking",
    "hillbillies",
    "hillbilly",
    "hindoo",
    "hiscock",
    "hitler",
    "hitlerism",
    "hitlerist",
    "hoare",
    "hobag",
    "hodgie",
    "hoer",
    "hoes",
    "holestuffer",
    "hom0",
    "homo",
    "homobangers",
    "homodumbshit",
    "homoey",
    "honger",
    "honkers",
    "honkey",
    "honkeys",
    "honkie",
    "honkies",
    "honky",
    "hooch",
    "hooker",
    "hookers",
    "hoor",
    "hoore",
    "hootch",
    "hooter",
    "hooters",
    "hore",
    "hori",
    "horis",
    "hork",
    "horndawg",
    "horndog",
    "horney",
    "horniest",
    "horny",
    "horseshit",
    "hosejob",
    "hoser",
    "hot carl",
    "hot chick",
    "hotcarl",
    "hotdamn",
    "hotpussy",
    "hotsex",
    "hottotrot",
    "how to kill",
    "how to murder",
    "howtokill",
    "howtomurdep",
    "huevon",
    "huge fat",
    "hugefat",
    "hui",
    "hummer",
    "humped",
    "humper",
    "humpher",
    "humphim",
    "humpin",
    "humping",
    "hussy",
    "hustler",
    "hymen",
    "hymie",
    "hymies",
    "iblowu",
    "ike",
    "ikes",
    "ikey",
    "ikeymo",
    "ikeymos",
    "ikwe",
    "illegals",
    "incest",
    "indon",
    "indons",
    "injun",
    "injuns",
    "insest",
    "intercourse",
    "intheass",
    "inthebuff",
    "israels",
    "j3rk0ff",
    "jack off",
    "jack-off",
    "jackass",
    "jackhole",
    "jackoff",
    "jackshit",
    "jacktheripper",
    "jail bait",
    "jailbait",
    "jap",
    "japcrap",
    "japie",
    "japies",
    "japs",
    "jebus",
    "jelly donut",
    "jerk off",
    "jerk-off",
    "jerk0ff",
    "jerked",
    "jerkoff",
    "jerries",
    "jerry",
    "jewboy",
    "jewed",
    "jewess",
    "jiga",
    "jigaboo",
    "jigaboos",
    "jigarooni",
    "jigaroonis",
    "jigg",
    "jigga",
    "jiggabo",
    "jiggaboo",
    "jiggabos",
    "jiggas",
    "jigger",
    "jiggerboo",
    "jiggers",
    "jiggs",
    "jiggy",
    "jigs",
    "jihad",
    "jijjiboo",
    "jijjiboos",
    "jimfish",
    "jisim",
    "jism",
    "jiss",
    "jiz",
    "jizim",
    "jizin",
    "jizjuice",
    "jizm",
    "jizn",
    "jizz",
    "jizzd",
    "jizzed",
    "jizzim",
    "jizzin",
    "jizzn",
    "jizzum",
    "jugg",
    "juggs",
    "jungle bunnies",
    "jungle bunny",
    "junglebunny",
    "junkie",
    "junky",
    "kacap",
    "kacapas",
    "kacaps",
    "kaffer",
    "kaffir",
    "kaffre",
    "kafir",
    "kanake",
    "kanker",
    "katsap",
    "katsaps",
    "kawk",
    "khokhol",
    "khokhols",
    "kigger",
    "kike",
    "kikes",
    "kimchis",
    "kinbaku",
    "kink",
    "kinkster",
    "kinky",
    "kinkyJesus",
    "kissass",
    "kiunt",
    "kkk",
    "klan",
    "klansman",
    "klansmen",
    "klanswoman",
    "klanswomen",
    "klootzak",
    "knobbing",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "knobz",
    "knockers",
    "knulle",
    "kock",
    "kondum",
    "kondums",
    "kooch",
    "kooches",
    "koon",
    "kootch",
    "krap",
    "krappy",
    "kraut",
    "krauts",
    "kuffar",
    "kuk",
    "kuksuger",
    "kum",
    "kumbubble",
    "kumbullbe",
    "kumer",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "kunnilingus",
    "kunt",
    "kunts",
    "kuntz",
    "kurac",
    "kurwa",
    "kushi",
    "kushis",
    "kusi",
    "kwa",
    "kwai lo",
    "kwai los",
    "kwif",
    "kyke",
    "kykes",
    "kyopo",
    "kyopos",
    "kyrpa",
    "l3i+ch",
    "l3i\\+ch",
    "l3itch",
    "labia",
    "lapdance",
    "leather restraint",
    "leather straight",
    "leatherrestraint",
    "lebos",
    "lech",
    "lemon party",
    "lemonparty",
    "leper",
    "lesbain",
    "lesbayn",
    "lesbin",
    "lesbo",
    "lesbos",
    "lez",
    "lezbe",
    "lezbefriends",
    "lezbian",
    "lezbians",
    "lezbo",
    "lezbos",
    "lezz",
    "lezzian",
    "lezzie",
    "lezzies",
    "lezzo",
    "lezzy",
    "libido",
    "licker",
    "licking",
    "lickme",
    "lilniglet",
    "limey",
    "limpdick",
    "limy",
    "lingerie",
    "lipshits",
    "lipshitz",
    "livesex",
    "loadedgun",
    "lolita",
    "lovebone",
    "lovegoo",
    "lovegun",
    "lovejuice",
    "lovemuscle",
    "lovepistol",
    "loverocket",
    "lowlife",
    "lsd",
    "lubejob",
    "lubra",
    "lucifer",
    "luckycammeltoe",
    "lugan",
    "lugans",
    "lusting",
    "lusty",
    "lynch",
    "m-fucking",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "mabuno",
    "mabunos",
    "macaca",
    "macacas",
    "mafugly",
    "magicwand",
    "mahbuno",
    "mahbunos",
    "make me come",
    "makemecome",
    "makemecum",
    "male squirting",
    "mamhoon",
    "mams",
    "manhater",
    "manpaste",
    "maricon",
    "maricón",
    "marijuana",
    "masochist",
    "masokist",
    "massa",
    "massterbait",
    "masstrbait",
    "masstrbate",
    "mastabate",
    "mastabater",
    "master-bate",
    "masterb8",
    "masterbaiter",
    "masterbat",
    "masterbat3",
    "masterbate",
    "masterbates",
    "masterbating",
    "masterbation",
    "masterbations",
    "masterblaster",
    "mastrabator",
    "masturbat",
    "masturbate",
    "masturbating",
    "masturbation",
    "mattressprincess",
    "mau mau",
    "mau maus",
    "maumau",
    "maumaus",
    "mcfagget",
    "meatbeatter",
    "meatrack",
    "menage",
    "merd",
    "mgger",
    "mggor",
    "mibun",
    "mick",
    "mickeyfinn",
    "mideast",
    "mierda",
    "milf",
    "mindfuck",
    "minge",
    "minger",
    "mo-fo",
    "mockey",
    "mockie",
    "mocky",
    "mof0",
    "mofo",
    "moky",
    "molest",
    "molestation",
    "molester",
    "molestor",
    "moneyshot",
    "mong",
    "monkleigh",
    "moolie",
    "moon cricket",
    "moon crickets",
    "mooncricket",
    "mooncrickets",
    "moron",
    "moskal",
    "moskals",
    "moslem",
    "mosshead",
    "motha fucker",
    "motha fuker",
    "motha fukkah",
    "motha fukker",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckaz",
    "mothafucked",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafucks",
    "mother fucker",
    "mother fukah",
    "mother fuker",
    "mother fukkah",
    "mother fukker",
    "mother-fucker",
    "motherfuck",
    "motherfucka",
    "motherfucked",
    "motherfucker",
    "motherfuckers",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckka",
    "motherfucks",
    "motherfvcker",
    "motherlovebone",
    "mothrfucker",
    "mouliewop",
    "mound of venus",
    "moundofvenus",
    "mr hands",
    "mrhands",
    "mtherfucker",
    "mthrfuck",
    "mthrfucker",
    "mthrfucking",
    "mtrfck",
    "mtrfuck",
    "mtrfucker",
    "muff diver",
    "muff",
    "muffdive",
    "muffdiver",
    "muffdiving",
    "muffindiver",
    "mufflikcer",
    "muffpuff",
    "muie",
    "mulatto",
    "mulkku",
    "muncher",
    "munging",
    "munt",
    "munter",
    "muschi",
    "mutha fucker",
    "mutha fukah",
    "mutha fuker",
    "mutha fukkah",
    "mutha fukker",
    "muthafecker",
    "muthafuckaz",
    "muthafucker",
    "muthafuckker",
    "muther",
    "mutherfucker",
    "mutherfucking",
    "muthrfucking",
    "mzungu",
    "mzungus",
    "n1gga",
    "n1gger",
    "n1gr",
    "nads",
    "naked",
    "nambla",
    "nastt",
    "nastybitch",
    "nastyho",
    "nastyslut",
    "nastywhore",
    "nawashi",
    "nazi",
    "nazis",
    "nazism",
    "necro",
    "needthedick",
    "negres",
    "negress",
    "negro",
    "negroes",
    "negroid",
    "negros",
    "neonazi",
    "nepesaurio",
    "nig nog",
    "nig",
    "niga",
    "nigar",
    "nigars",
    "nigas",
    "nigers",
    "nigette",
    "nigettes",
    "nigg",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggahs",
    "niggar",
    "niggaracci",
    "niggard",
    "niggarded",
    "niggarding",
    "niggardliness",
    "niggardlinesss",
    "niggardly",
    "niggards",
    "niggars",
    "niggas",
    "niggaz",
    "nigger",
    "niggerhead",
    "niggerhole",
    "niggers",
    "niggle",
    "niggled",
    "niggles",
    "nigglings",
    "niggor",
    "niggress",
    "niggresses",
    "nigguh",
    "nigguhs",
    "niggur",
    "niggurs",
    "niglet",
    "nignog",
    "nigor",
    "nigors",
    "nigr",
    "nigra",
    "nigras",
    "nigre",
    "nigres",
    "nigress",
    "nigs",
    "nigur",
    "niiger",
    "niigr",
    "nimphomania",
    "nimrod",
    "ninny",
    "nipple",
    "nipplering",
    "nipples",
    "nips",
    "nittit",
    "nlgger",
    "nlggor",
    "nob jokey",
    "nob",
    "nobhead",
    "nobjocky",
    "nobjokey",
    "nofuckingway",
    "nog",
    "nookey",
    "nookie",
    "nooky",
    "noonan",
    "nooner",
    "nsfw images",
    "nsfw",
    "nudger",
    "nudie",
    "nudies",
    "numbnuts",
    "nut sack",
    "nutbutter",
    "nutfucker",
    "nutsack",
    "nutten",
    "nympho",
    "nymphomania",
    "o c k",
    "octopussy",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "one guy",
    "one jar",
    "ontherag",
    "orafis",
    "orga",
    "orgasim",
    "orgasim;",
    "orgasims",
    "orgasm",
    "orgasmic",
    "orgasms",
    "orgasum",
    "orgies",
    "orgy",
    "oriface",
    "orifiss",
    "orospu",
    "osama",
    "ovum",
    "ovums",
    "p e n i s",
    "p i s",
    "p u s s y",
    "p.u.s.s.y.",
    "p0rn",
    "packi",
    "packie",
    "packy",
    "paddy",
    "paedophile",
    "paki",
    "pakie",
    "pakis",
    "paky",
    "palesimian",
    "pancake face",
    "pancake faces",
    "panooch",
    "pansies",
    "pansy",
    "panti",
    "pantie",
    "panties",
    "panty",
    "paska",
    "payo",
    "pcp",
    "pearlnecklace",
    "pecker",
    "peckerhead",
    "peckerwood",
    "pedo",
    "pedobear",
    "pedophile",
    "pedophilia",
    "pedophiliac",
    "peeenus",
    "peeenusss",
    "peehole",
    "peenus",
    "peepee",
    "peepshow",
    "peepshpw",
    "pegging",
    "peinus",
    "pen1s",
    "penas",
    "pendejo",
    "pendy",
    "penetrate",
    "penetration",
    "peni5",
    "penial",
    "penile",
    "penis",
    "penis-breath",
    "penises",
    "penisfucker",
    "penisland",
    "penislick",
    "penislicker",
    "penispuffer",
    "penthouse",
    "penus",
    "penuus",
    "perse",
    "perv",
    "perversion",
    "peyote",
    "phalli",
    "phallic",
    "phone sex",
    "phonesex",
    "phuc",
    "phuck",
    "phuk",
    "phuked",
    "phuker",
    "phuking",
    "phukked",
    "phukker",
    "phukking",
    "phuks",
    "phungky",
    "phuq",
    "pi55",
    "picaninny",
    "piccaninny",
    "picka",
    "pickaninnies",
    "pickaninny",
    "piece of shit",
    "pieceofshit",
    "piefke",
    "piefkes",
    "pierdol",
    "pigfucker",
    "piker",
    "pikey",
    "piky",
    "pillowbiter",
    "pillu",
    "pimmel",
    "pimp",
    "pimped",
    "pimper",
    "pimpis",
    "pimpjuic",
    "pimpjuice",
    "pimpsimp",
    "pindick",
    "pinko",
    "pis",
    "pises",
    "pisin",
    "pising",
    "pisof",
    "piss pig",
    "piss",
    "piss-off",
    "pissed",
    "pisser",
    "pissers",
    "pisses",
    "pissflap",
    "pissflaps",
    "pisshead",
    "pissin",
    "pissing",
    "pissoff",
    "pisspig",
    "pizda",
    "playboy",
    "playgirl",
    "pleasure chest",
    "pleasurechest",
    "pocha",
    "pochas",
    "pocho",
    "pochos",
    "pocketpool",
    "pohm",
    "pohms",
    "polac",
    "polack",
    "polacks",
    "polak",
    "pole smoker",
    "polesmoker",
    "pollock",
    "pollocks",
    "pommie grant",
    "pommie grants",
    "pommy",
    "ponyplay",
    "poof",
    "poon",
    "poonani",
    "poonany",
    "poontang",
    "poontsee",
    "poop chute",
    "poopchute",
    "pooper",
    "pooperscooper",
    "pooping",
    "poorwhitetrash",
    "popimp",
    "porch monkey",
    "porch monkies",
    "porchmonkey",
    "porn",
    "pornflick",
    "pornking",
    "porno",
    "pornography",
    "pornos",
    "pornprincess",
    "pound town",
    "poundtown",
    "pplicker",
    "pr0n",
    "pr1c",
    "pr1ck",
    "pr1k",
    "prairie nigger",
    "prairie niggers",
    "preteen",
    "pric",
    "prickhead",
    "pricks",
    "prig",
    "prince albert piercing",
    "pron",
    "prostitute",
    "pthc",
    "pu55i",
    "pu55y",
    "pube",
    "pubes",
    "pubic",
    "pubiclice",
    "pubis",
    "pudboy",
    "pudd",
    "puddboy",
    "pula",
    "punani",
    "punanny",
    "punany",
    "punkass",
    "punky",
    "punta",
    "puntang",
    "purinapricness",
    "pusies",
    "puss",
    "pusse",
    "pussee",
    "pussi",
    "pussie",
    "pussies",
    "pussy",
    "pussycat",
    "pussydestroyer",
    "pussyeater",
    "pussyfart",
    "pussyfuck",
    "pussyfucker",
    "pussylicker",
    "pussylicking",
    "pussylips",
    "pussylover",
    "pussypalace",
    "pussypounder",
    "pussys",
    "pusy",
    "puta",
    "puto",
    "puuke",
    "puuker",
    "qahbeh",
    "quashie",
    "queaf",
    "queef",
    "queerhole",
    "queero",
    "queers",
    "queerz",
    "quickie",
    "quicky",
    "quiff",
    "quim",
    "qweers",
    "qweerz",
    "qweir",
    "r-tard",
    "r-tards",
    "r5e",
    "ra8s",
    "raghead",
    "ragheads",
    "rape",
    "raped",
    "raper",
    "raping",
    "rapist",
    "rautenberg",
    "rearend",
    "rearentry",
    "recktum",
    "rectal",
    "rectum",
    "rectus",
    "redleg",
    "redlegs",
    "redlight",
    "redskin",
    "redskins",
    "reefer",
    "reestie",
    "reetard",
    "reich",
    "renob",
    "rentafuck",
    "rere",
    "retard",
    "retarded",
    "retards",
    "retardz",
    "reverse cowgirl",
    "reversecowgirl",
    "rimjaw",
    "rimjob",
    "rimming",
    "ritard",
    "rosebuds",
    "rosy palm and her 5 sisters",
    "rosy palm",
    "rosypalm",
    "rosypalmandher5sisters",
    "rosypalmandherefivesisters",
    "round eyes",
    "roundeye",
    "rtard",
    "rtards",
    "rumprammer",
    "ruski",
    "russki",
    "russkie",
    "rusty trombone",
    "rustytrombone",
    "s h i t",
    "s hit",
    "s&m",
    "s-h-1-t",
    "s-h-i-t",
    "s-o-b",
    "s.h.i.t.",
    "s.o.b.",
    "s0b",
    "s_h_i_t",
    "sadis",
    "sadism",
    "sadist",
    "sadom",
    "sambo",
    "sambos",
    "samckdaddy",
    "sanchez",
    "sand nigger",
    "sand niggers",
    "sandm",
    "sandnigger",
    "santorum",
    "sausagequeen",
    "scag",
    "scallywag",
    "scank",
    "scantily",
    "scat",
    "schaffer",
    "scheiss",
    "schizo",
    "schlampe",
    "schlong",
    "schmuck",
    "schvartse",
    "schvartsen",
    "schwartze",
    "schwartzen",
    "scissoring",
    "screwyou",
    "scroat",
    "scrog",
    "scrote",
    "scrotum",
    "scrud",
    "seduce",
    "semen",
    "seppo",
    "seppos",
    "septics",
    "sex",
    "sexcam",
    "sexed",
    "sexfarm",
    "sexhound",
    "sexhouse",
    "sexi",
    "sexing",
    "sexkitten",
    "sexo",
    "sexpot",
    "sexslave",
    "sextogo",
    "sextoy",
    "sextoys",
    "sexual",
    "sexually",
    "sexwhore",
    "sexx",
    "sexxi",
    "sexxx",
    "sexxxi",
    "sexxxy",
    "sexxy",
    "sexy",
    "sexymoma",
    "sexyslim",
    "sh!+",
    "sh!t",
    "sh1t",
    "sh1ter",
    "sh1ts",
    "sh1tter",
    "sh1tz",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "shamedame",
    "sharmuta",
    "sharmute",
    "shat",
    "shav",
    "shaved beaver",
    "shaved pussy",
    "shavedbeaver",
    "shavedpussy",
    "shawtypimp",
    "sheeney",
    "shemale",
    "shhit",
    "shi+",
    "shibari",
    "shibary",
    "shinola",
    "shipal",
    "shit ass",
    "shit",
    "shit-ass",
    "shit-bag",
    "shit-bagger",
    "shit-brain",
    "shit-breath",
    "shit-cunt",
    "shit-dick",
    "shit-eating",
    "shit-face",
    "shit-faced",
    "shit-fit",
    "shit-head",
    "shit-heel",
    "shit-hole",
    "shit-house",
    "shit-load",
    "shit-pot",
    "shit-spitter",
    "shit-stain",
    "shitass",
    "shitbag",
    "shitbagger",
    "shitblimp",
    "shitbrain",
    "shitbreath",
    "shitcan",
    "shitcunt",
    "shitdick",
    "shite",
    "shiteater",
    "shiteating",
    "shited",
    "shitey",
    "shitface",
    "shitfaced",
    "shitfit",
    "shitforbrains",
    "shitfuck",
    "shitfucker",
    "shitfull",
    "shithapens",
    "shithappens",
    "shithead",
    "shitheel",
    "shithole",
    "shithouse",
    "shiting",
    "shitings",
    "shitlist",
    "shitload",
    "shitola",
    "shitoutofluck",
    "shitpot",
    "shits",
    "shitspitter",
    "shitstain",
    "shitt",
    "shitted",
    "shitter",
    "shitters",
    "shittiest",
    "shitting",
    "shittings",
    "shitty",
    "shity",
    "shitz",
    "shiz",
    "shiznit",
    "shortfuck",
    "shota",
    "shylock",
    "shylocks",
    "shyt",
    "shyte",
    "shytty",
    "shyty",
    "simp",
    "sissy",
    "sixsixsix",
    "sixtynine",
    "sixtyniner",
    "skag",
    "skanck",
    "skank",
    "skankbitch",
    "skankee",
    "skankey",
    "skankfuck",
    "skanks",
    "skankwhore",
    "skanky",
    "skankybitch",
    "skankywhore",
    "skeet",
    "skinflute",
    "skribz",
    "skullfuck",
    "skum",
    "skumbag",
    "skurwysyn",
    "skwa",
    "skwe",
    "slag",
    "slanteye",
    "slanty",
    "slapper",
    "sleezeball",
    "slideitin",
    "slimeball",
    "slimebucket",
    "slopehead",
    "slopeheads",
    "sloper",
    "slopers",
    "slopey",
    "slopeys",
    "slopies",
    "slopy",
    "slut",
    "slutbag",
    "slutbucket",
    "slutdumper",
    "slutkiss",
    "sluts",
    "slutt",
    "slutting",
    "slutty",
    "slutwear",
    "slutwhore",
    "slutz",
    "smackthemonkey",
    "smeg",
    "smegma",
    "smut",
    "smutty",
    "snatchpatch",
    "sniggered",
    "sniggering",
    "sniggers",
    "snowback",
    "snowballing",
    "snownigger",
    "snuff",
    "socksucker",
    "sodom",
    "sodomise",
    "sodomite",
    "sodomize",
    "sodomy",
    "son of a bitch",
    "son of a whore",
    "son-of-a-bitch",
    "son-of-a-whore",
    "sonofabitch",
    "sonofbitch",
    "sooties",
    "souse",
    "soused",
    "soyboy",
    "spac",
    "spaghettibender",
    "spaghettinigger",
    "spank",
    "spankthemonkey",
    "spastic",
    "spearchucker",
    "spearchuckers",
    "sperm",
    "spermacide",
    "spermbag",
    "spermhearder",
    "spermherder",
    "sphencter",
    "spic",
    "spick",
    "spicks",
    "spics",
    "spierdalaj",
    "spig",
    "spigotty",
    "spik",
    "spiks",
    "splittail",
    "splooge",
    "spludge",
    "spooge",
    "spread legs",
    "spreadeagle",
    "spunk",
    "spunky",
    "sqeh",
    "squa",
    "squarehead",
    "squareheads",
    "squaw",
    "squinty",
    "squirting",
    "stagg",
    "stfu",
    "stiffy",
    "stoned",
    "stoner",
    "strap on",
    "strapon",
    "strappado",
    "strip club",
    "stripclub",
    "stroking",
    "stuinties",
    "stupidfuck",
    "stupidfucker",
    "style doggy",
    "suckdick",
    "sucked",
    "sucker",
    "sucking",
    "suckme",
    "suckmyass",
    "suckmydick",
    "suckmytit",
    "suckoff",
    "suicide girl",
    "suicide girls",
    "suicidegirl",
    "suicidegirls",
    "suka",
    "sultrywoman",
    "sultrywomen",
    "sumofabiatch",
    "swallower",
    "swalow",
    "swamp guinea",
    "swamp guineas",
    "swastika",
    "syphilis",
    "t i t",
    "t i ts",
    "t1t",
    "t1tt1e5",
    "t1tties",
    "tacohead",
    "tacoheads",
    "taff",
    "take off your",
    "tar babies",
    "tar baby",
    "tarbaby",
    "tard",
    "taste my",
    "tastemy",
    "tawdry",
    "tea bagging",
    "teabagging",
    "teat",
    "teets",
    "teez",
    "terd",
    "teste",
    "testee",
    "testes",
    "testical",
    "testicle",
    "testicles",
    "testis",
    "thicklip",
    "thicklips",
    "thirdeye",
    "thirdleg",
    "threesome",
    "threeway",
    "throating",
    "thumbzilla",
    "thundercunt",
    "tied up",
    "tig ol bitties",
    "tig old bitties",
    "tight white",
    "timber nigger",
    "timber niggers",
    "timbernigger",
    "tit",
    "titbitnipply",
    "titfuck",
    "titfucker",
    "titfuckin",
    "titi",
    "titjob",
    "titlicker",
    "titlover",
    "tits",
    "titt",
    "tittie",
    "tittie5",
    "tittiefucker",
    "titties",
    "tittis",
    "titty",
    "tittyfuck",
    "tittyfucker",
    "tittys",
    "tittywank",
    "titwank",
    "tity",
    "to murder",
    "tongethruster",
    "tongue in a",
    "tongueina",
    "tonguethrust",
    "tonguetramp",
    "toots",
    "topless",
    "tortur",
    "torture",
    "tosser",
    "towel head",
    "towel heads",
    "towelhead",
    "trailertrash",
    "trannie",
    "tranny",
    "transsexual",
    "transvestite",
    "tribadism",
    "trisexual",
    "trois",
    "trots",
    "tub girl",
    "tubgirl",
    "tuckahoe",
    "tunneloflove",
    "turd burgler",
    "turnon",
    "tush",
    "tushy",
    "tw4t",
    "twat",
    "twathead",
    "twatlips",
    "twats",
    "twatty",
    "twatwaffle",
    "twink",
    "twinkie",
    "two girls one cup",
    "twobitwhore",
    "twunt",
    "twunter",
    "udge packer",
    "ukrop",
    "unclefucker",
    "unfuckable",
    "upskirt",
    "uptheass",
    "upthebutt",
    "urethra play",
    "urethraplay",
    "urophilia",
    "usama",
    "ussys",
    "uzi",
    "v a g i n a",
    "v14gra",
    "v1gra",
    "v4gra",
    "va-j-j",
    "va1jina",
    "vag",
    "vag1na",
    "vagiina",
    "vaj1na",
    "vajina",
    "valium",
    "venus mound",
    "vgra",
    "vibr",
    "vibrater",
    "vibrator",
    "vigra",
    "violet wand",
    "virginbreaker",
    "vittu",
    "vixen",
    "vjayjay",
    "vorarephilia",
    "voyeurweb",
    "voyuer",
    "vullva",
    "vulva",
    "w00se",
    "w0p",
    "wab",
    "wang",
    "wank",
    "wanker",
    "wanking",
    "wanky",
    "waysted",
    "wazoo",
    "weenie",
    "weewee",
    "weiner",
    "welcher",
    "wench",
    "wet dream",
    "wetb",
    "wetback",
    "wetbacks",
    "wetdream",
    "wetspot",
    "wh00r",
    "wh0re",
    "wh0reface",
    "whacker",
    "whash",
    "whigger",
    "whiggers",
    "whiskeydick",
    "whiskydick",
    "whit",
    "white power",
    "white trash",
    "whitenigger",
    "whitepower",
    "whitetrash",
    "whitey",
    "whiteys",
    "whities",
    "whoar",
    "whop",
    "whoralicious",
    "whore",
    "whorealicious",
    "whorebag",
    "whored",
    "whoreface",
    "whorefucker",
    "whorehopper",
    "whorehouse",
    "whores",
    "whoring",
    "wichser",
    "wigga",
    "wiggas",
    "wigger",
    "wiggers",
    "willie",
    "willies",
    "williewanker",
    "willy",
    "wog",
    "wogs",
    "woose",
    "wop",
    "worldsex",
    "wrapping men",
    "wrinkled starfish",
    "wtf",
    "wuss",
    "wuzzie",
    "x-rated",
    "x-rated2g1c",
    "xkwe",
    "xrated",
    "xtc",
    "xx",
    "xxx",
    "xxxxxx",
    "yank",
    "yaoi",
    "yarpie",
    "yarpies",
    "yed",
    "yellow showers",
    "yellowman",
    "yellowshowers",
    "yid",
    "yids",
    "yiffy",
    "yobbo",
    "yourboobs",
    "yourpenis",
    "yourtits",
    "yury",
    "zabourah",
    "zigabo",
    "zigabos",
    "zipperhead",
    "zipperheads",
    "zoophile",
    "zoophilia",
    "🖕",
    "skibidi",
    "skibidi toilet",
    "gyatt",
    "rizz",
    "only in ohio",
    "ohio",
    "duke dennis",
    "did you pray today",
    "livvy dunne rizzing up baby gronk",
    "livvy dunne",
    "baby gronk",
    "sussy imposter",
    "sus",
    "sussy baka",
    "pibby glitch in real life",
    "sigma",
    "alpha",
    "omega",
    "andrew tate",
    "goon cave",
    "freddy fazbear",
    "colleen ballinger",
    "smurf cat",
    "strawberry elephant",
    "blud",
    "dawg",
    "shlawg",
    "bill collector",
    "I'm nothing like yall",
    "ishowspeed",
    "a whole bunch of turbulence",
    "ambatukam",
    "bro really thinks he's carti",
    "literally hitting the griddy",
    "the ocky way",
    "kai cenat",
    "fanum tax",
    "garten of banban",
    "no edging in class",
    "edge",
    "not the mosquito again",
    "bussin",
    "axel in harlem",
    "whopper whopper whopper whopper",
    "1 2 buckle my shoe",
    "goofy ahh",
    "aiden ross",
    "sin city",
    "monday left me broken",
    "quirked up",
    "white boy busting it down",
    "goated with the sauce",
    "john pork",
    "john pork is calling",
    "grimace shake",
    "kiki do you love me",
    "huggy wuggy",
    "nathaniel b",
    "lightskin stare",
    "biggest bird",
    "omar the referee",
    "amogus",
    "uncanny",
    "wholesome",
    "reddit",
    "chungus",
    "big chungus",
    "bill clungus",
    "keanu reeves",
    "pizza tower",
    "zesty poggers",
    "kumalala savesta",
    "quandale dingle",
    "glizzy",
    "rose toy",
    "ankha zone",
    "thug shaker",
    "morbin time",
    "dj khaled",
    "sisyphus",
    "oceangate",
    "shadow wizard money gang",
    "ayo the pizza here",
    "PLUH",
    "nair butthole waxing",
    "t-pose",
    "ugandan knuckles",
    "family guy funny moments compilation",
    "subway surfers gameplay",
    "nickeh30",
    "ratio",
    "uwu",
    "delulu",
    "opium bird",
    "cg5",
    "mewing",
    "fortnite battle pass",
    "all my fellas",
    "gta 6",
    "backrooms",
    "gigachad",
    "based",
    "cringe",
    "redpilled",
    "no nut november",
    "nonstop nut november",
    "pokénut november",
    "foot fetish",
    "F in the chat",
    "i love lean",
    "looksmaxxing",
    "social credit",
    "bing chilling",
    "xbox live",
    "mrbeast",
    "kid named finger",
    "better caul saul",
    "i am a surgeon",
    "hit or miss i guess they never miss huh",
    "i like ya cut g",
    "ice spice",
    "gooning",
    "fr",
    "we go gym",
    "kevin james",
    "josh hutcherson",
    "coffin of andy and leyley",
    "metal pipe falling",
    "low taper fade",
    "DATTEBAYO",
    "GYATTEBAYO",
    "do you like my sword?",
    "808s",
    "one pandemonium door 30 please",
    "jonkler",
    "patrick bateman",
    "why did he do that? Is he stupid?",
    "I just lost my dog",
    "what the fuck is a kilometer",
    "bro thought I was new",
    "I need more boulets",
    "german stare",
    "jamaican smile",
    "balkan rage",
    "flow state",
    "goon",
    "I'll take a Double Triple Bossy Deluxe on a raft, four by four, animal-style, extra shingles with a shimmy and a squeeze, light axle grease, make it cry, burn it, and let it swim",
    "pomni",
    "marriah carrey defrosting",
    "still water",
    "english or spanish",
    "flickergoon",
    "hawk tuah",
    "lunchly",
    "kris tyson",
    "karl jacobs",
    "feastables",
    "boi",
    "blud",
    "those who know",
    "prime",
    "thick of it",
    "talk tuah",
    "ninja",
    "hailey welch",
    "sneako",
    "I like my cheese drippy bruh",
    "bruh",
    "troll face",
    "why so serious",
    "fein",
    "FEIN",
    "FE!N",
    "fin fin fin",
    "IDKsterling",
    "it's the first of the month",
    "a potato flew around my room",
    "rick rave",
    "jonkler",
    "meru the succubus",
    "derpixon",
    "minus8",
    "chaturbate",
    "jerkmate",
    "put that cookie down",
    "do the roar",
    "everywhere at the end of time",
    "heart aches",
    "libets delay",
    "mango phonk",
    "phonk",
    "thomas shelby",
    "lone wolf sigma chad",
    "put the phone down",
    "this is for my safety",
    "bryan cranston dance",
    "finger",
    "walt",
    "walter white",
    "breaking bad",
    "better call saul",
    "saul goodman",
    "jesse pinkman",
    "skyler white yo",
    "#NEVERGOON",
    "#ALWAYSGOON",
    "I have a dream",
    "winter arc",
    "hey there are you for real I'm for real real",
    "frickin",
    "adrenaline",
    "nonadrenaline",
    "noradrenaline",
    "nokotan",
    "ya like jazz?",
    "user8687391766990",
    "oh when the saints",
    "why so skibidi",
    "absolute cinema",
    "hawk 1: what's 1+1? hawk 2: uhh",
    "alya",
    "honey pie",
    "toothless",
    "boy it's just alcohol",
    "kurt angel",
    "oi oi oi",
    "ei ei ei",
    "do not the cat",
    "demure",
    "matpat",
    "lankybox",
    "physics.",
    "jojo reference",
    "made in heaven",
    "maiden heaven",
    "blumpkin",
    "drippy cheese",
    "squid game",
    "in new york I milly rock",
    "yes king",
    "uwu",
    "owo",
    "spaceX",
    "ligma",
    "2024",
    "2023",
    "2025",
    "duolingo",
    "cherry blossom ice tea",
    "venom",
    "hog rider",
    "fire in the hole",
    "water on the hill",
    "shrimp alfredo",
    "caseoh",
    "what the sigma",
    "erm",
    "america ya",
    "hell naw",
    "gedagedigedagedago",
    "you are my sunshine",
    "lebron james",
    "your final challenge",
    "we can go gyatt for gyatt",
    "500 cigarettes",
    "freakbob",
    "diddy",
    "diddy party",
    "edp445",
    "let’s go gambling",
    "xiao hong shu",
    "I am steve",
    "I’m just ken",
    "hatsune miku",
    "coomer miku",
    "I just lost my dog",
    "ding dong eat it up",
    "homelander",
    "patrick bateman",
    "the fog is coming",
    "never back down never what",
    "nickeh30",
    "you think you’re the king?",
    "I gently open the door…",
    "thug shaker",
    "I am a surgeon",
    "monday left me broken",
    "dylan page",
    "hood irony",
    "steezus christ",
    "dancing walking rearranging furniture",
    "obama prism",
    "I don’t understand this grilled cheese obama sandwich",
    "life is roblox",
    "sisyphus",
    "ambatukam",
    "dreamybull",
    "strawberry elephant",
    "smurf cat",
    "markiplier",
    "erosion bird",
    "I got 2 phones",
    "sticking out your gyatt for the rizzler",
    "there is nothing we can do",
    "chestnuts roasting on an open fire",
    "last rizzmas I gave you my gyatt",
    "put the stillwater down",
    "your phone linging",
    "I’m spongebob",
    "you’re so portuguese",
    "metro boomin make it boom",
    "oh my gah",
    "mods crush his skull",
    "mods nuke his house",
    "sui",
    "talking ben",
    "can we get much higher",
    "APT",
    "just monika",
    "DDLC",
    "drippy cheese",
    "falcon punch",
    "mom get the camera",
    "bocci",
    "cyberpunk 2077",
    "mike tyson",
    "mike tyson vs jake paul",
    "jake paul",
    "logan paul",
    "I think I saw someone hanging over there",
    "sonic feet",
    "feet pics",
    "foot fetish",
    "feet",
    "hairytwinkle",
    "xqc",
    "is that dew dew",
    "stanky leg",
    "homer uchiha",
    "phonk",
    "DJ Sigma",
    "COVID",
    "coronavirus",
    "amogus",
    "ayoo sussy",
    "ayo",
    "sus",
    "bluelock season 2",
    "I understand it now",
    "I'm still alive and kicking",
    "are you crying?",
    "subtle foreshadowing",
    "brunchly",
    "individuals who possess knowledge on the subject at hand",
    "tony hawk hawk tuah I aint talkin to ya",
    "skibidi slicers",
    "mousepay",
    "freakpay",
    "pay gorn",
    "sesbian lex",
    "da boyz",
    "are these the worlds most crispy fries?",
    "gail lewis",
    "queen never cry",
    "george droyd",
    "ambatron",
    "niggachain",
    "floydtech",
    "why is everything chrome",
    "I just be playing lego gta",
    "chill guy",
    "jugging",
    "huzz",
    "bruzz",
    "greetings huzz",
    "salutations fine shyts",
    "thuzz whuzz knuzz",
    "chopped shyt",
    "fine shyt",
    "duzz",
    "muzz",
    "fuzz",
    "homer sharingan",
    "know your meme",
    "AI minecraft",
    "rick roll",
    "trump",
    "kamala",
    "biden",
    "obama",
    "obamna",
    "super idol",
    "yo dudes the empire is pretty chill",
    "it’s wednesday my dudes",
    "say that again",
    "emotional damage",
    "brainrot",
    "zyzz",
    "sturdy",
    "rizz party",
    "kumalala",
    "savesta",
    "chesta",
    "unc",
    "lil bro",
    "rainbolt",
    "REEEE",
    "E",
    "lmanburg",
    "asdfmovie",
    "dame tu cosita",
    "we are number one",
    "daquavious pork pay",
    "newgen",
    "hurricane katrina",
    "may god bless you with mountains of gold and silver",
    "xiao hong shu",
    "chat",
    "*inhales* BOII",
    "funkytown",
    "give a nigga a break",
    "martial law",
    "lost media",
    "well well well",
    "butterball turkey",
    "big brother is watching you",
    "calc is short for calculator",
    "calc",
    "yunc",
    "yn",
    "fn",
    "green fn",
    "colossal shyt",
    "trollface",
    "doge",
    "cheems",
    "pepe",
    "meatspin",
    "here come dat boi",
    "2 girls 1 cup",
    "dank memes",
    "rule 34",
    "rule 63",
    "nyan cat",
    "momo",
    "stonks",
    "this is fine",
    "kek",
    "the cake is a lie",
    "it's over 9000",
    "leeroy jenkins",
    "crazy? I was crazy once. they locked me in a room. a rubber room. a rubber room with rats. and rats make me crazy",
    "tidepod challenge",
    "no this is patrick",
    "pewdiepie",
    "t-series",
    "coomer",
    "sanic",
    "nokia 3310",
    "the one piece is real",
    "shadman",
    "no bitches?",
    "*tips fedora*",
    "you ladies alright?",
    "padoru padoru",
    "T-pose",
    "NPC",
    "epic fail",
    "saddam hussein",
    "saddam hussein hiding spot",
    "death note",
    "who's getting the best head?",
    "let him cook",
    "poggers",
    "pog",
    "pogchamp",
    "earth-chan",
    "animan studios",
    "trypophobia",
    "69",
    "420",
    "69420",
    "21",
    "I forgor",
    "le monke",
    "bepis",
    "nah I'd win",
    "sonic.exe",
    "SCP",
    "I like turtles",
    "it's corn",
    "dummy thicc",
    "ara ara",
    "ya like jazz?",
    "crab rave",
    "you've been gnomed",
    "immortal snail",
    "YOLO",
    "coca cola espuma",
    "mario judah",
    "the sun is a deadly laser",
    "I baked you a pie",
    "muffin time",
    "never back down never give up",
    "knee surgery",
    "that feeling when knee surgery is tomorrow",
    "don pollo",
    "geekbob",
    "perc 30s",
    "nettspend",
    "rod wave",
    "crash out",
    "geeking",
    "big justice",
    "withered big justice",
    "chopped huzz",
    "chuzz",
    "all time low",
    "tiktok",
    "vine",
    "youtube shorts",
    "stop it, get some help",
    "DO IT, JUST DO IT",
    "well well well",
    "dave blunts",
    "darius",
    "laufey",
    "slay",
    "yass",
    "ate",
    "yeet",
    "you’re not that guy pal",
    "I will always serve you",
    "Zach D Films",
    "MLG",
    "360 no-scope",
    "baby yoda",
    "that was legitness",
    "I aint pray for these baguettes I pray for better days",
    "Juice WRLD",
    "XXXTentacion",
    "pop smoke",
    "you know what else is massive?",
    "It’s not the miyagido way",
    "those who are employed",
    "naruto run",
    "skibidi sheldon",
    "young sheldon",
    "the mannii show",
    "kiirkiimad",
    "ryan reynolds",
    "dhar mann",
    "touch me I scream",
    "skibidi minion",
    "king baldwin",
    "big bad wolf",
    "emu otori",
    "wonderhoy",
    "block blast",
    "brawl stars",
    "melodie",
    "melodie vs beethoven",
    "keys",
    "carterpcs",
    "broski",
    "luigi manguine",
    "quintessential quintuplets",
    "the coffin of Andy and Leyley",
    "lemme syd",
    "mama owl",
    "takis",
    "deez nuts",
    "ts",
    "ts (this)",
    "pmo",
    "ts pmo",
    "sybau",
    "ts tmo",
    "MASSIVE",
    "mods slaughter his family",
    "brazillian miku",
    "can you believe it guys? Christmas is in a week!",
    "wojak",
    "king von",
    "king von anti piracy",
    "anita max wynn",
    "quirked up white boy with a little bit of swag busts it down sexual style.. is he goated with the sauce?",
    "truth nuke",
    "incel",
    "femcel",
    "moid",
    "foid",
    "UnitedHealthcare CEO",
    "Cooking with Kya",
    "yandere simulator",
    "MiSide",
    "$TUAH",
    "dandadan",
    "marvel rivals",
    "zesty cow",
    "no chick-fil-a sauce?",
    "4 seasons orlando",
    "galaxy gas",
    "vape",
    "fent",
    "fentanyl",
    "paracetemol",
    "gojo figure incident",
    "this shit is so ass",
    "based",
    "bjork",
    "lobotomy",
    "verbalase 50k",
    "free luigi",
    "I like my suitcase",
    "fortnite, we need to talk.",
    "becoming stronger than your dad:",
    "I like trains",
    "everybody do the flop",
    "I am a stegosaurus",
    "it says gullible on the ceiling",
    "when life gives you lemons",
    "I guess you are my little pogchamp",
    "you're my honeybunch sugarplum",
    "GET OUT",
    "hentaihaven",
    "ROFL",
    "xD",
    "pornhub",
    "watermelon river",
    "5x30 5Min/Day",
    "locked in alien",
    "vexbolts",
    "linganguli guli guli",
    "chug jug with you",
    "what is the next step of the operation?",
    "vexbolts mass unfollowing",
    "pen pineapple apple pen",
    "coffin dance",
    "two steps ahead",
    "nicocado avocado",
    "bashame",
    "ishowmeat",
    "alan walker",
    "minecraft vs real life",
    "noob vs pro vs hacker vs god",
    "luh calm fit",
    "eye of rah",
    "geeked vs locked in",
    "bop house",
    "sophie rain",
    "sophie rain spiderman",
    "mia khalifa",
    "ChatGPT",
    "AI",
    "drake",
    "munt",
    "munting",
    "jelqing",
    "dab",
    "floss",
    "tiktok rizz party",
    "femboy",
    "tomboy",
    "bbg",
    "abg",
    "3am",
    "saitama",
    "goku",
    "vegita",
    "roflcopter",
    "pewdiepie vs t-series",
    "brofist",
    "subscribe to pewdiepie",
    "bitch lasagna",
    "cartoon beatbox battles",
    "epic rap battles of history",
    "jacksepticeye",
    "danTDM",
    "diamond minecart",
    "minecraft",
    "minecraft movie",
    "fortnite",
    "roblox",
    "somebody toucha my spaghet",
    "nya ichi ni san nya arigato",
    "aura",
    "fiveish",
    "bombastic side eye",
    "criminally offensive side eye",
    "side eye",
    "morbillion",
    "morbius",
    "man or bear",
    "beast games",
    "lock in",
    "chopped chin",
    "I bought a property in egypt",
    "locked in ninja",
    "druski",
    "raise your yayaya",
    "just give me my money",
    "thanos",
    "bas kitty",
    "just put the fries in the bag",
    "I feel so sigma!",
    "I used to shop at aldi",
    "aldi",
    "this is my perfect victory",
    "squid game season 2",
    "I've been running into you in my head",
    "leave vexbolts in 2024",
    "neopronouns",
    "avocados from mexico",
    "airpod shotty",
    "ayo chill the fuck out yo",
    "light yagami",
    "chickawagga",
    "binley mega chippy",
    "thanos car",
    "tuff",
    "kevin g",
    "perchance",
    "you can't just say perchance",
    "devious lick",
    "edging streak",
    "mewing streak",
    "dance till you're dead",
    "ricardo milos",
    "pepe the frog",
    "dababy",
    "dababy convertible",
    "less go",
    "bite the curb",
    "curbstomp",
    "hi my name is carmen winstead",
    "carmen winstead",
    "omaygot",
    "ambatublow",
    "NSFW",
    "porn",
    "hentai",
    "waifu",
    "lolicon",
    "futanari",
    "shota",
    "mr belding",
    "xvideos",
    "nhentai",
    "hanime",
    "candylove",
    "sweetiefox",
    "edgemaxxing",
    "ropemaxxing",
    "relax liberals, it's called dark humor",
    "edge sesh",
    "goon sesh",
    "meatcanyon",
    "costco guys",
    "we're costco guys",
    "kamala harris",
    "donald trump",
    "joe biden",
    "felch",
    "you digging in me",
    "who made that mess",
    "what's up brother",
    "let's go gambling",
    "twomad",
    "what twomad saw",
    "90% of gamblers quit just before they hit it big",
    "turkish quandale dingle",
    "blue tie kid",
    "white shirt kid",
    "big bird sesame big minge energy",
    "sketch",
    "trollge",
    "mr incredible",
    "elastigirl",
    "aunt cass",
    "imagine if ninja got a low taper fade",
    "skibidi sigma pomni digital fortnite chamba free gigachad rizz omaiga floo xxxtentacion smurf cat lionel ronaldo junior mewing tercero chikibay xocas insano",
    "yusuf dikeç",
    "unc status",
    "kai cenat save us",
    "chrissy wake up",
    "my dog stepped on a bee",
    "deny defend depose",
    "cute winter boots",
    "elon musk salute",
    "goonicide",
    "gooneral",
    "goonlord",
    "detect detain deport",
    "raw, next question",
    "mr washee washee",
    "veiny ahh dih",
    "germanrot",
    "what's that? what's a father?",
    "pop out at 1 in the morning",
    "loss meme",
    "jerkmate ranked",
    "HTA1ITM",
    "because bread tastes better than key",
    "AI kwebbelkop",
    "shi is bubonic",
    "dih",
    "hawk tuah at 1 in the morning",
    "POA1ITM",
    "rappers who can sing vs rappers who can't sing",
    "beabadoobee",
    "tim cheese",
    "the great meme depression",
    "McDonalds in the pentagon",
    "I like to cuss like I was raised in a barn",
    "meme drought",
    "dont touch my pizza",
    "ashton hall",
    "saratoga water",
    "coming in hot",
    "steves lava chicken",
    "hot lava and chicken",
    "water bucket release",
    "crushing loafs",
    "flint and steel",
    "the nether",
    "chicken jockey",
    "bugrock",
    "I got a brand new saxophone",
    "the big bros",
    "jepaloon productions",
    "agartha",
    "vril",
    "save europe",
    "jack black",
    "lil phoebe"
  ];
// --- Middleware ---
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
app.use(express.static(path.join(__dirname, 'public')));

// --- Basic HTML Escaping Helper ---
function escapeHtml(unsafe) {
    if (typeof unsafe !== 'string') return "";
    return unsafe
         .replace(/&/g, "&") // Correct escaping
         .replace(/</g, "<")
         .replace(/>/g, ">")
         .replace(/"/g, "\"")
         .replace(/'/g, "'"); // Use HTML entity for single quote
 }

// --- In-Memory Reservation Store ---
let reservations = [];
const RESERVATION_DURATION_MINUTES = 120; // 2 hours
const CAPACITY_LIMIT = 20; // Max concurrent guests (adjust as needed)
const TIME_SLOT_INTERVAL = 30; // Minutes between slots
const VERIFICATION_EXPIRY_MINUTES = 15;

// List of standard available time slots (30 min intervals)
const AVAILABLE_TIMES = [
    "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30",
    "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", "18:30",
    "19:00", "19:30", "20:00", "20:30", "21:00" // Last booking slot
];
// Define closing time for "past" check more accurately
const KITCHEN_CLOSE_TIME = "21:30"; // When kitchen actually closes

// --- In-Memory Review Store (Keep as is) ---
let reviews = [
    // Example initial review (optional)
    { id: 'initial1', name: 'Alice G.', stars: 5, text: 'Absolutely loved the atmosphere and the food! The Green Curry was spectacular. Will definitely be back.', createdAt: moment().subtract(2, 'days').toISOString() },
    { id: 'initial2', name: null, stars: 4, text: 'Great place for vegetarians. Service was a bit slow during peak hours, but the food quality made up for it.', createdAt: moment().subtract(1, 'day').toISOString() }
];
let reviewIdCounter = reviews.length;

// --- Helper: Calculate Occupancy at a Specific Time ---
function calculateOccupancy(targetDateTime) {
    let currentOccupancyAtTime = 0;
    const slotStartTime = moment(targetDateTime); // Ensure it's a moment object
    // Calculate when a reservation *starting* at this time would end
    const slotEndTime = moment(slotStartTime).add(RESERVATION_DURATION_MINUTES, 'minutes');

    reservations.forEach(res => {
        // *** Only count CONFIRMED reservations for occupancy check ***
        if (res.status !== 'confirmed') {
            return;
        }

        // Calculate start and end times for the existing confirmed reservation
        let resStartTime = moment(`${res.date} ${res.time}`, "YYYY-MM-DD HH:mm");
        let resEndTime = moment(resStartTime).add(RESERVATION_DURATION_MINUTES, 'minutes');

        // Check for overlap: Does the existing reservation clash with the potential new slot?
        // Overlap occurs if: (Existing Start < Slot End) AND (Existing End > Slot Start)
        if (resStartTime.isBefore(slotEndTime) && resEndTime.isAfter(slotStartTime)) {
            // Ensure numberOfPeople is treated as a number
            currentOccupancyAtTime += parseInt(res.numberOfPeople, 10) || 0;
        }
    });
    return currentOccupancyAtTime;
}

// --- Reservation Processing Logic (Keep mostly as is, add check against AVAILABLE_TIMES) ---
function processReservation(request) {
    return new Promise((resolve, reject) => {
        const { name, email, date, time, numberOfPeople, specialRequests } = request;

        // Basic Validation
        if (!name || !email || !date || !time || !numberOfPeople) {
            return reject("Missing required reservation information.");
        }
        const numPeople = parseInt(numberOfPeople, 10);
        if (isNaN(numPeople) || numPeople < 1) {
            return reject("Invalid number of people specified.");
        }
        if (numPeople > 8) {
            return reject(`For parties larger than 8, please call us at ${RESTAURANT_PHONE}.`);
        }

        // Date/Time Validation
        let requestedDateTime = moment(`${date} ${time}`, "YYYY-MM-DD HH:mm");
        if (!requestedDateTime.isValid()) {
            return reject("Invalid date or time format. Please use YYYY-MM-DD and HH:mm.");
        }
        // Ensure the selected time is one of the official slots
        if (!AVAILABLE_TIMES.includes(time)) {
             return reject(`Invalid time selected (${escapeHtml(time)}). Please choose from the available slots.`);
        }
        // Prevent booking too close to now or in the past
        if (requestedDateTime.isBefore(moment().add(15, 'minutes'))) { // Require at least 15 mins notice
            return reject("Cannot make reservations less than 15 minutes in advance or for a past time.");
        }

        // *** Capacity Check (Using helper for CONFIRMED reservations) ***
        const currentOccupancy = calculateOccupancy(requestedDateTime);
        console.log(`Checking capacity for: ${requestedDateTime.format("YYYY-MM-DD HH:mm")} | Guests requested: ${numPeople} | Current confirmed occupancy: ${currentOccupancy} | Capacity Limit: ${CAPACITY_LIMIT}`);

        if (currentOccupancy + numPeople > CAPACITY_LIMIT) {
            const availableSeats = Math.max(0, CAPACITY_LIMIT - currentOccupancy); // Ensure non-negative
            console.warn(`Capacity exceeded for ${date} ${time}. Requested: ${numPeople}, Occupancy: ${currentOccupancy}, Limit: ${CAPACITY_LIMIT}`);
            return reject(`Unfortunately, we are fully booked for a party of ${numPeople} at ${moment(time, "HH:mm").format("h:mm A")}. ${availableSeats > 0 ? `Only ${availableSeats} seat(s) remaining.` : 'No seats remaining at this time.'} Please try a different time or date.`);
        }

        // Generate unique reservation ID and verification token
        let reservationId = Date.now().toString(36) + crypto.randomBytes(4).toString('hex');
        let verificationToken = crypto.randomBytes(20).toString('hex');
        let verificationExpires = moment().add(VERIFICATION_EXPIRY_MINUTES, 'minutes');

        let newReservation = {
            id: reservationId,
            name: escapeHtml(name.trim()), // Escape user input on save
            email: email.trim().toLowerCase(), // Don't escape email
            date: date,
            time: time,
            numberOfPeople: numPeople,
            specialRequests: specialRequests ? escapeHtml(specialRequests.trim()) : "", // Escape user input
            requestedAt: moment().toISOString(),
            verified: false,
            verificationToken: verificationToken,
            verificationExpires: verificationExpires.toISOString(),
            status: 'pending_verification'
        };

        reservations.unshift(newReservation);
        console.log("Reservation pending verification:", newReservation);
        resolve(newReservation);
    });
}

// --- Email Configuration (Nodemailer) ---
const mailFrom = `"Green Bites Reservations" <${MAIL_USER}>`;
let transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: { user: MAIL_USER, pass: MAIL_PASS },
});
transporter.verify((error, success) => {
    if (error) console.error('Nodemailer verification failed:', error);
    else console.log('Nodemailer is ready to send emails.');
});

// --- API Endpoints ---

// *** NEW: GET /availability - Provide time slot status for a date ***
app.get('/availability', (req, res) => {
    const { date, partySize } = req.query;

    if (!date || !moment(date, 'YYYY-MM-DD', true).isValid()) {
        return res.status(400).json({ error: 'Valid date parameter (YYYY-MM-DD) is required.' });
    }
    if (moment(date).isBefore(moment().startOf('day'))) {
         return res.status(400).json({ error: 'Cannot check availability for past dates.' });
    }

    const requestedPartySize = parseInt(partySize, 10);
    if (isNaN(requestedPartySize) || requestedPartySize < 1) {
         return res.status(400).json({ error: 'Invalid partySize parameter. Must be 1 or greater.' });
    }
    // Check against max online booking size
    if (requestedPartySize > 8) {
        // Return empty slots with a specific message instead of error? Or keep error?
        // Let's return empty slots and let frontend handle message.
        console.warn(`Availability check for party size ${requestedPartySize} > 8. Returning empty.`);
        return res.status(200).json({
             date: date,
             requestedPartySize: requestedPartySize,
             capacityLimit: CAPACITY_LIMIT,
             slots: [], // Empty array signifies call needed
             message: `Party size ${requestedPartySize} is too large for online booking. Please call.`
         });
   }

    const now = moment();
    const kitchenCloseDateTime = moment(`${date} ${KITCHEN_CLOSE_TIME}`, "YYYY-MM-DD HH:mm");

    const availability = AVAILABLE_TIMES.map(timeSlot => {
        const slotDateTime = moment(`${date} ${timeSlot}`, "YYYY-MM-DD HH:mm");
        let status = 'unknown';
        let availableSeats = 0;

        // Check if the slot start time is in the past or too close to now
        // Allow checking slots starting *now* or slightly in the past if interval is large
        if (slotDateTime.isBefore(now.subtract(TIME_SLOT_INTERVAL / 2, 'minutes'))) {
            status = 'past';
            availableSeats = 0;
        }
        // Check if slot is after kitchen closes (or too close to it)
        else if (slotDateTime.isAfter(kitchenCloseDateTime.subtract(RESERVATION_DURATION_MINUTES / 2, 'minutes'))) {
            status = 'past'; // Treat as past/unavailable if it's too late
            availableSeats = 0;
        }
         else {
            // Calculate occupancy using *confirmed* reservations
            const occupancy = calculateOccupancy(slotDateTime);
            availableSeats = Math.max(0, CAPACITY_LIMIT - occupancy); // Ensure non-negative

            if (availableSeats >= requestedPartySize) {
                status = 'available';
            } else if (availableSeats <= 0) {
                status = 'full';
            } else {
                // Seats available, but not enough for the *requested* party size
                status = 'limited';
            }
        }

        return {
            time: timeSlot, // e.g., "18:30"
            displayTime: moment(timeSlot, "HH:mm").format("h:mm A"), // e.g., "6:30 PM"
            status: status, // 'available', 'full', 'limited', 'past'
            availableSeats: availableSeats
        };
    });

    res.status(200).json({
        date: date,
        requestedPartySize: requestedPartySize,
        capacityLimit: CAPACITY_LIMIT,
        slots: availability
    });
});

// POST /reserve - Handle new reservation requests (Keep as is, uses processReservation)
app.post('/reserve', async (req, res) => {
    console.log("Received reservation request:", req.body);
    try {
        const reservationRequest = req.body;
        const pendingReservation = await processReservation(reservationRequest);

        const protocol = req.protocol;
        const host = req.get("host");
        const verificationLink = `${protocol}://${host}/verify?resId=${pendingReservation.id}&token=${pendingReservation.verificationToken}`;

        // Send Verification Email
        const mailOptions = {
             from: mailFrom,
             to: pendingReservation.email,
             subject: 'Confirm Your Reservation at Green Bites!',
             html: verificationEmailTemplate(pendingReservation, verificationLink, VERIFICATION_EXPIRY_MINUTES),
        };

        try {
            let info = await transporter.sendMail(mailOptions);
            console.log('Verification email sent:', info.messageId, 'to', pendingReservation.email);
            res.status(200).json({
                success: true,
                message: `Verification email sent to ${escapeHtml(pendingReservation.email)}! Please check your inbox (and spam folder) to confirm within ${VERIFICATION_EXPIRY_MINUTES} minutes.`
            });
        } catch (mailError) {
            console.error("Error sending verification email:", mailError);
            reservations = reservations.filter(r => r.id !== pendingReservation.id); // Rollback
            console.log("Removed pending reservation due to email failure:", pendingReservation.id);
            res.status(500).json({
                success: false,
                error: 'Could not send verification email. Your reservation failed. Please check the email address or contact us directly.'
            });
        }

    } catch (err) {
        console.error("Error processing reservation request:", err);
        res.status(400).json({ success: false, error: err || "Failed to process reservation request." });
    }
});


// GET /verify - Handle email verification links (Keep as is)
app.get('/verify', (req, res) => {
    const { resId, token } = req.query;
    console.log(`Verification attempt - ID: ${resId}, Token present: ${!!token}`);

    if (!resId || !token) {
         console.warn(`Verification failed: Missing resId or token.`);
         return res.status(400).send(verificationResponsePage("Verification Failed", "The verification link is incomplete.", "error"));
    }

    const reservationIndex = reservations.findIndex(r => r.id === resId);
    if (reservationIndex === -1) {
         console.warn(`Verification failed: Reservation ID ${resId} not found.`);
         return res.status(404).send(verificationResponsePage("Verification Failed", "We couldn't find a pending reservation matching this link. It might have expired or been confirmed/cancelled.", "error"));
    }

    const reservation = reservations[reservationIndex];

    if (reservation.status === 'confirmed') {
          console.log(`Verification redundant: ID ${resId} already confirmed.`);
          return res.status(200).send(verificationResponsePage("Already Confirmed", `Your reservation for ${reservation.numberOfPeople} guest(s) on ${moment(reservation.date).format("MMM D, YYYY")} at ${moment(reservation.time, "HH:mm").format("h:mm A")} is already confirmed!`, "success"));
     }
    if (reservation.status !== 'pending_verification') {
        console.warn(`Verification failed: ID ${resId} has status '${reservation.status}'.`);
        return res.status(410).send(verificationResponsePage("Link No Longer Valid", `This link is no longer valid (status: '${escapeHtml(reservation.status)}'). Please make a new reservation.`, "error"));
    }
    if (moment().isAfter(moment(reservation.verificationExpires))) {
        console.warn(`Verification failed: Token expired for ID ${resId}.`);
        reservation.status = 'expired_unverified';
        reservation.verificationToken = null;
        reservations[reservationIndex] = reservation;
        return res.status(410).send(verificationResponsePage("Verification Expired", `Sorry, this link expired (valid for ${VERIFICATION_EXPIRY_MINUTES} minutes). Please make a new reservation.`, "error"));
    }
    if (reservation.verificationToken !== token) {
        console.warn(`Verification failed: Invalid token for ID ${resId}.`);
         return res.status(400).send(verificationResponsePage("Verification Failed", "Invalid verification link or token.", "error"));
    }

    // --- Verification SUCCESS ---
    console.log(`Verification SUCCESS for ID: ${resId}, Email: ${reservation.email}`);
    reservation.status = 'confirmed';
    reservation.verificationToken = null;
    reservation.verificationExpires = null;
    reservation.verifiedAt = moment().toISOString();
    reservations[reservationIndex] = reservation;
    console.log(`Reservation CONFIRMED: ID ${resId}, Name: ${reservation.name}, Date: ${reservation.date}, Time: ${reservation.time}, Guests: ${reservation.numberOfPeople}`);

    sendConfirmationEmail(reservation).catch(err => {
        console.error(`Error sending confirmation email for ${resId}:`, err);
    });

    // Use pre-escaped values from the reservation object
    res.status(200).send(verificationResponsePage(
        "Reservation Confirmed!",
        `Thank you, ${reservation.name}! Your reservation for ${reservation.numberOfPeople} guest(s) on <strong>${moment(reservation.date).format("dddd, MMMM Do, YYYY")}</strong> at <strong>${moment(reservation.time, "HH:mm").format("h:mm A")}</strong> is confirmed. ${reservation.specialRequests ? '<br/><br/>Noted request: "' + reservation.specialRequests + '"': ''}<br/><br/>We look forward to welcoming you!`,
        "success"
        ));
});

// --- GET /reviews & POST /reviews (Keep as is) ---
app.get('/reviews', (req, res) => {
    const sortedReviews = [...reviews].sort((a, b) => moment(b.createdAt).diff(moment(a.createdAt)));
    res.status(200).json(sortedReviews);
});
app.post('/reviews', (req, res) => {
    console.log("Received review submission:", req.body);
    const { name, stars, text } = req.body;
    var isOffensive = false;
    badWords.forEach(phrase => {
        if(text.toLowerCase().includes(phrase) || text.includes(phrase)) isOffensive = true;
    });
    if(!isOffensive){
        const rating = parseInt(stars, 10);
        if (!rating || isNaN(rating) || rating < 1 || rating > 5) {
            return res.status(400).json({ success: false, error: 'A valid star rating (1-5) is required.' });
        }
        const MAX_TEXT_LENGTH = 1000;
        const reviewText = text && typeof text === 'string' ? text.trim().slice(0, MAX_TEXT_LENGTH) : null;
        const reviewerName = name && typeof name === 'string' ? name.trim().slice(0, 50) : null;
        const newReview = {
            id: `rev_${Date.now()}_${reviewIdCounter++}`,
            name: reviewerName ? escapeHtml(reviewerName) : null,
            stars: rating,
            text: reviewText ? escapeHtml(reviewText) : null,
            createdAt: moment().toISOString()
        };
        reviews.unshift(newReview);
        console.log("New review added:", newReview);
        res.status(201).json({ success: true, message: 'Thank you for your review!', review: newReview });
    } else {
        res.status(403).json({ success: false, error: 'Please do not include offensive terms, profanity, brainrot, or slang in your review and try again.', review: null });
    }
});


// --- Helper Function for HTML Verification Response Page (Keep as is) ---
function verificationResponsePage(title, message, status = "info") {
    let backgroundColor = '#e0f2fe'; let textColor = '#075985'; let icon = 'ℹ️';
    if (status === 'success') { backgroundColor = '#dcfce7'; textColor = '#166534'; icon = '✅'; }
    else if (status === 'error') { backgroundColor = '#fee2e2'; textColor = '#991b1b'; icon = '❌'; }
    return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${escapeHtml(title)} - Green Bites</title><style>body{font-family:sans-serif;margin:0;padding:0;background-color:#f3f4f6;display:flex;justify-content:center;align-items:center;min-height:100vh;}.container{background-color:#fff;padding:30px 40px;border-radius:8px;box-shadow:0 4px 12px rgba(0,0,0,0.1);text-align:center;max-width:500px;margin:20px;}h1{color:#333;margin:0 0 15px;font-size:1.8em;}.status-box{background-color:${backgroundColor};color:${textColor};border-radius:6px;padding:15px;margin-top:20px;border:1px solid ${textColor}30;}.status-box p{margin:0;font-size:1.1em;line-height:1.6;}.icon{font-size:2em;display:block;margin-bottom:10px;}.footer{margin-top:25px;font-size:0.9em;color:#6b7280;}a{color:#1d4ed8;text-decoration:none;}a:hover{text-decoration:underline;}</style></head><body><div class="container"><h1>${escapeHtml(title)}</h1><div class="status-box"><span class="icon">${icon}</span><p>${message}</p></div><div class="footer"><p>Return to <a href="/">Green Bites Home</a></p><p>Questions? Call us at ${RESTAURANT_PHONE}</p></div></div></body></html>`;
}

// --- Helper Function for Verification Email HTML (Keep as is) ---
function verificationEmailTemplate(reservation, verificationLink, expiryMinutes) {
    const formattedDate = moment(reservation.date).format("dddd, MMMM Do, YYYY");
    const formattedTime = moment(reservation.time, "HH:mm").format("h:mm A");
    const formattedExpiry = moment(reservation.verificationExpires).format("h:mm A z");
    // Use pre-escaped values from reservation object
    return `<!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Confirm Your Reservation</title> <style> body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; } .container { padding: 20px; max-width: 600px; margin: 20px auto; border: 1px solid #ddd; border-radius: 8px; background-color: #f9f9f9; } h2 { color: #2c5282; } p { margin-bottom: 15px; } strong { color: #1a202c; } .details { background-color: #fff; padding: 15px; border-radius: 5px; margin-bottom: 20px; border: 1px solid #eee; } .details strong { display: inline-block; min-width: 100px; } .button-container { text-align: center; margin: 25px 0; } .button { background-color: #48bb78; color: white !important; padding: 12px 25px; text-decoration: none; border-radius: 5px; font-weight: bold; font-size: 16px; display: inline-block; } .button:hover { background-color: #38a169; } .expires { font-size: 0.9em; color: #718096; text-align: center; margin-top: 5px; } .footer { margin-top: 20px; font-size: 0.85em; text-align: center; color: #a0aec0; } </style> </head> <body> <div class="container"> <h2>Confirm Your Reservation at Green Bites</h2> <p>Hello ${reservation.name},</p> <p>Please confirm your reservation details below and click the button to verify:</p> <div class="details"> <p><strong>Name:</strong> ${reservation.name}</p> <p><strong>Date:</strong> ${formattedDate}</p> <p><strong>Time:</strong> ${formattedTime}</p> <p><strong>Guests:</strong> ${reservation.numberOfPeople}</p> ${reservation.specialRequests ? `<p><strong>Requests:</strong> ${reservation.specialRequests}</p>` : ''} </div> <p>Confirm within <strong style="color: #dd6b20;">${expiryMinutes} minutes</strong>:</p> <div class="button-container"> <a href="${verificationLink}" target="_blank" class="button">Verify My Reservation</a> </div> <p class="expires">Link expires around ${formattedExpiry}.</p> <p>If you didn't request this, please ignore this email.</p> <hr style="border: none; border-top: 1px solid #eee; margin: 20px 0;"> <p>Sincerely,<br>The Green Bites Team</p> <div class="footer"> <p>Green Bites | 123 Green Way, Fairfax, VA | ${RESTAURANT_PHONE}</p> </div> </div> </body> </html>`;
}


// --- Helper Function for Confirmation Email HTML (Keep as is) ---
function confirmationEmailTemplate(reservation) {
    const formattedDate = moment(reservation.date).format("dddd, MMMM Do, YYYY");
    const formattedTime = moment(reservation.time, "HH:mm").format("h:mm A");
    // Use pre-escaped values from reservation object
    return `<!DOCTYPE html> <html lang="en"> <head> <meta charset="UTF-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Reservation Confirmed!</title> <style> body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; } .container { padding: 20px; max-width: 600px; margin: 20px auto; border: 1px solid #ddd; border-radius: 8px; background-color: #f9f9f9; } h2 { color: #38a169; } p { margin-bottom: 15px; } strong { color: #1a202c; } .details { background-color: #fff; padding: 15px; border-radius: 5px; margin-bottom: 20px; border: 1px solid #eee; } .details strong { display: inline-block; min-width: 100px; } .footer { margin-top: 20px; font-size: 0.85em; text-align: center; color: #a0aec0; } </style> </head> <body> <div class="container"> <h2>Your Green Bites Reservation is Confirmed!</h2> <p>Hello ${reservation.name},</p> <p>This email confirms your reservation details:</p> <div class="details"> <p><strong>Name:</strong> ${reservation.name}</p> <p><strong>Date:</strong> ${formattedDate}</p> <p><strong>Time:</strong> ${formattedTime}</p> <p><strong>Guests:</strong> ${reservation.numberOfPeople}</p> ${reservation.specialRequests ? `<p><strong>Requests:</strong> ${reservation.specialRequests}</p>` : ''} </div> <p>We look forward to welcoming you!</p> <p><strong>Notes:</strong> Please arrive 5-10 minutes early. If plans change, contact us. We are at 123 Green Way, Fairfax, VA.</p> <p>Sincerely,<br>The Green Bites Team</p> <div class="footer"> <p>Green Bites | 123 Green Way, Fairfax, VA | ${RESTAURANT_PHONE}</p> </div> </div> </body> </html>`;
}


// --- Optional Confirmation Email Function (Keep as is) ---
async function sendConfirmationEmail(reservation) {
    console.log(`Sending confirmation email to ${reservation.email} for ID: ${reservation.id}`);
    const mailOptions = {
        from: mailFrom, to: reservation.email,
        subject: `Confirmed: Green Bites Reservation ${moment(reservation.date).format("MMM D")} at ${moment(reservation.time, "HH:mm").format("h:mm A")}`,
        html: confirmationEmailTemplate(reservation)
    };
    try {
        let info = await transporter.sendMail(mailOptions);
        console.log('Confirmation email sent:', info.messageId); return info;
    } catch (error) {
        console.error(`Failed confirmation email to ${reservation.email} for ${reservation.id}:`, error); throw error;
    }
}


// --- Cleanup Interval (Keep as is) ---
setInterval(() => {
    const now = moment(); let markedExpiredCount = 0;
    reservations.forEach((res, index) => {
        if (res.status === 'pending_verification' && moment(res.verificationExpires).isBefore(now)) {
            console.log(`Auto-expiring pending reservation: ID ${res.id}`);
            reservations[index].status = 'expired_unverified';
            reservations[index].verificationToken = null; markedExpiredCount++;
        }
    });
    if (markedExpiredCount > 0) console.log(`Cleanup marked ${markedExpiredCount} as 'expired_unverified'.`);
    // Optional: Purge old confirmed/past/cancelled reservations
    // Optional: Purge old reviews
}, 10 * 60 * 1000); // Every 10 minutes


// --- Admin endpoint (Keep as is) ---
app.get('/current-reservations', (req, res) => {
    const apiKey = req.query.apiKey;
    if (!apiKey || apiKey !== ADMIN_API_KEY) {
        return res.status(401).json({ error: 'Unauthorized' });
    }
    const sortedReservations = [...reservations].sort((a, b) => moment(`${a.date} ${a.time}`).diff(moment(`${b.date} ${b.time}`)));
    const safeReservations = sortedReservations.map(r => ({...r, verificationToken: undefined, verificationExpires: undefined}));
    res.status(200).json({ count: safeReservations.length, reservations: safeReservations });
});

// GET / - Serve the main page (index.html)
app.get('/', (req, res) => {
    res.sendFile(path.join(__dirname, 'public', 'index.html'));
});

// Serve other HTML files directly if needed (assuming they are in public)
app.get('/:pageName.html', (req, res, next) => {
    const pageName = req.params.pageName;
    // Basic security check: only allow alphanumeric page names
    if (/^[a-zA-Z0-9_-]+$/.test(pageName)) {
        const filePath = path.join(__dirname, 'public', `${pageName}.html`);
        res.sendFile(filePath, (err) => {
            if (err) { // Handle file not found or other errors
                console.log(`Error serving ${pageName}.html:`, err.status);
                if (err.status === 404) {
                    next(); // Pass to 404 handler if file doesn't exist
                } else {
                    next(err); // Pass other errors to the global error handler
                }
            }
        });
    } else {
        next(); // Invalid page name format, treat as 404
    }
});


// --- Global Error Handler (Keep as is) ---
app.use((err, req, res, next) => {
    console.error("Unhandled Error:", err.stack || err);
    if (res.headersSent) { return next(err); }
    if (req.accepts('json')) {
        res.status(500).json({ error: 'Internal Server Error' });
    } else {
         res.status(500).send(verificationResponsePage('Server Error', 'Oops! Something went wrong on our end. Please try again later.', 'error'));
    }
});

// --- 404 Handler (Added for better handling of unknown routes) ---
app.use((req, res, next) => {
    res.status(404).send(verificationResponsePage('Page Not Found', 'Sorry, the page you are looking for does not exist.', 'error'));
});


// --- Start Server ---
app.listen(PORT, () => {
    console.log(`-------------------------------------------------------`);
    console.log(` Green Bites Server Listening on http://localhost:${PORT}`);
    console.log(` Static files served from: ${path.join(__dirname, 'public')}`);
    console.log(` Restaurant Phone: ${RESTAURANT_PHONE}`);
    console.warn(` >>> Data is IN-MEMORY and LOST on restart! <<<`);
    console.warn(` >>> Ensure MAIL_USER/PASS (App Password) & ADMIN_KEY are set. <<<`);
    console.log(`-------------------------------------------------------`);
});